### ISSUE TITLE
DynamicMethodTrait__call: Add method name to Exception

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/core#111]
Hello,

this is a typical PHPUnit output:
```
1) BookingTest::testDiscountCodeMToM
atk4\core\Exception: Method is not defined for this object
```
Of course, having the method name in the exception message would help a lot, like
```
1) BookingTest::testDiscountCodeMToM
atk4\core\Exception: Method myNonExsistantMethod is not defined for this object
```

If no one objects, I would implement this, its a very simple adjustment in DynamicMethodTrait->__call().

**Comment by DarkSide666** [comment]
merged
