### ISSUE TITLE
Idea: Seed to support hooks.

### ISSUE THREAD

**Issue by romaninsh** [atk4/core#112]
Currently hooks support properties:

``` php
$this->factory([Some::class, 'jsCallback'=>function() {});
```

However it's not important to inject hooks! The idea is to extend factory support to allow placement of hooks through factory:

``` php
$this->factory([Some::class, 'hook:afterExecute'=>[ function(){} ]);
```

When merging seeds, hooks will be also combined, since we support hooks well. Also we can introduce advanced syntax if hook priority should be specified inside hook array.

**Comment by mvorisek** [comment]
@romaninsh Always specify why, some specific existing & strong usecase.

**Comment by DarkSide666** [comment]
Probably that would be ability to define hooks inside seed. Could be useful, but probably not much.

**Comment by mvorisek** [comment]
Of course, but what is the config where it makes a good sense?

I know a one usecase - for init hook so we can change something which seed can not. But init has currently no hooks.

**Comment by DarkSide666** [comment]
I can't think of other usecase too.

**Comment by mvorisek** [comment]
Closing, reopen/add support once there is a real use case
