### ISSUE TITLE
Configuration Elements cannot be replaced

### ISSUE THREAD

**Issue by bepixeld** [atk4/core#118]
If multiple configuration files are used, a configuration item cannot be replaced.
e.g. Standard Configuration with User Configuration.
default: `$config['lang' => 'en'];`
user: `$config['lang' => 'de'];`
Calling `$obj->getConfig('lang')` returns an array `['en', 'de']`.
However, the string 'de' would be desired.
Is there a special reason why `array_merge_recursive` is used?
This can be prevented with `array_replace_recursive`.
Thanks in advance for an explanation.
See #117

**Comment by DarkSide666** [comment]
Thanks for noticing. Yes `array_replace_recursive` should be used there.
