### ISSUE TITLE
Multiple hooks for one action can be added, but they have to be currently deleted completely

### ISSUE THREAD

**Issue by mvorisek** [atk4/core#131]
See https://github.com/atk4/core/blob/develop/src/HookTrait.php#L98

Specific hook should be possible to delete by name and priority.

**Comment by PhilippGrashoff** [comment]
very good one! So we need an optional ident to set to a hook so we can identify it for removal, e.g.
`$this->removeHook('afterSave', 'createNotifications');` Or how would you approach accessing each hook individually?

**Comment by mvorisek** [comment]
@PhilippGrashoff "optional ident" would be the best, but as different priority can be set, for most of the purposes optional "priority parameter in remove method" would be enought and implementing should be very easy + there would be 100% backcompatibility. Wdyt?

**Comment by DarkSide666** [comment]
Can you give me one real-life use-case when deleting hooks is useful?
I think it's the same as with model conditions which sets model scope - no need to actually delete them.

**Comment by mvorisek** [comment]
@DarkSide666 I have some custom persistence manager. And if this manager is used, hook is added to the managed object when processing and removed when done.

When the object is not processed thru this manager instance, the hook should never be fired. Of course, it can we solved differently, but I do not see any issue with this approach.

With this PR also one-time hooks can be code very easily.

**Comment by PhilippGrashoff** [comment]
@DarkSide666 a very simple example is if you use save() in an afterSave() hook. This leads to an infinite save() after save().
This is taken from my code to ship around that:
```
    /**
     *
     */
    public function emptyCalendarCache($save = true)
    {
        $this->_exceptionIfThisNotLoaded();
        $this->set('calendar_row_cache', null);
        $this->set('calendar_cache', null);
        //Prevent multiple saves by some actions
        if ($this->isDirty(['calendar_row_cache', 'calendar_cache'])) {
            $this->set('last_updated', new DateTime());
        }
        if ($save) {
            //work on clone as all the hooks take a lot of time and lead to infinite save()
            $clone = clone($this);
            $clone->removeHook('afterSave');
            $clone->removeHook('beforeSave');
            $clone->removeHook('beforeUpdate');
            $clone->removeHook('afterUpdate');
            $clone->reload_after_save = false;
            $clone->save();
        }
    }
```

**Comment by DarkSide666** [comment]
I see. So, yes, maybe that can be handy in these situations, but still should be used with care.
