### ISSUE TITLE
When hook for the same spot is added from hook itself, it is removed once the hook finish

### ISSUE THREAD

**Issue by mvorisek** [atk4/core#137]
https://github.com/atk4/core/blob/0d922e092f7ccd20efe29d197e84c5387d718565/src/HookTrait.php#L186

Is this desired and why?

**Comment by DarkSide666** [comment]
I think it should be like that because it will execute hooks one by one and pop them out of this->hooks array. When all hooks are executed, then we have to restore hook setup. That's in case same hook sequence need to be executed again for same object.
Think about data model afterSave hooks for example. It can save records multiple times, so afterSave hook sequence should be executed multiple times.

**Comment by mvorisek** [comment]
Reasoning makes sense from this POV, but is this usual in other libs? Where it is used like this? In past I also added an option to remove hooks, so I think these rare cases if any should be solved that way.

Adding a permanent hook inside hook might be fully legit. I also this it is broken now if you add hook inside hook from another type (so the reasoning above does not apply)

ping @romaninsh @DarkSide666

**Comment by DarkSide666** [comment]
This has to be carefully discussed and definitely including @romaninsh.
I think this should not be changed because it's quite common that particular hook sequence can be executed multiple times.

**Comment by mvorisek** [comment]
@DarkSide666 provide real examples where it is used like so - I think this is only a bad design and even it does not work all the time (see my comment above + the code)

**Comment by DarkSide666** [comment]
I think something like this should do:
```
$m->onHook($m::HOOK_AFTER_SAVE, function(){...});
$m->onHook($m::HOOK_AFTER_SAVE, function(){...});

$m->save(['name' => 'foo']); // execute both hook callbacks
$m->unload(); // unload if new record, not unload to update same record

$m->save(['name' => 'bar']); // also should execute both callbacks so we can't remove them from $m->hooks array while executing 
```

**Comment by mvorisek** [comment]
I propose to test the proposed behaviour (ie. not depended on execution context) on real repos

**Comment by DarkSide666** [comment]
Yes. That's why I set this _on standby_ not _wont fix_ :)
Maybe it's a bug, but need to spend some time to make sure. Not now.

**Comment by mvorisek** [comment]
`standby` label should be never added, it is very unclear what you mean. I assigned in under myself, will test soon

**Comment by mvorisek** [comment]
minimal repro needed
