### ISSUE TITLE
Display where \Closure was defined in exception trace

### ISSUE THREAD

**Issue by mvorisek** [atk4/core#149]
Very important for fast debug and even more important in Atk, where closures/callbacks are used a lot.

Location can be obtained via Reflection.

Example:
![image](https://user-images.githubusercontent.com/2228672/78788616-58d65a00-79ac-11ea-9693-a3fb505e990e.png)

**Comment by mvorisek** [comment]
I can propose a PR, is it welcomed?

**Comment by DarkSide666** [comment]
Yes that's definitely welcome if possible!

**Comment by mvorisek** [comment]
```
<?php

function dump_closure_details(callable $fx) {
    $r = new \ReflectionFunction($fx);
    var_dump($r->getFileName() . ':' . $r->getStartLine());
}

class Test {
    public function ex() {
        $fx = function() {
            return new \Exception();
        };
        dump_closure_details($fx);
        return $fx();
    }
    
    public function trace() {
        $fx = function() {
            return debug_backtrace();
        };
        dump_closure_details($fx);
        return $fx();
    }
}

$ex = (new Test())->ex();
var_dump($ex->getTrace()[0]); // res['function'] is string...


$trace = (new Test())->trace();
var_dump($trace[0]); // res['function'] is string...

// how to get the original closure from the exception trace or backtrace?
```

Hmm, it seems like a hard limitation of PHP. Not sure if the original Closure object can be even obtained with xdebug.

Any hint welcomed.

Also asking core PHP people about it.

**Comment by mvorisek** [comment]
PR to `php-src` engine needs to be submitted first, see https://bugs.php.net/bug.php?id=62325

**Comment by mvorisek** [comment]
Closing as currently there is no support from PHP side
