### ISSUE TITLE
mergeSeeds ignores arguments if already instanced

### ISSUE THREAD

**Issue by mvorisek** [atk4/core#190]
see https://github.com/atk4/core/blob/5fb3fbe55684f7a1c63389d021750507293668d5/src/FactoryTrait.php#L37
`$arguments` are ignored. Of couse, they can not be passed to constructor anymore as already instanced, but shouln't this result in an exception?

**Comment by DarkSide666** [comment]
Yes numeric arguments at this point are useless so they are not used.
Should we throw exception? Not completely sure about that. Currently it doesn't do that and it's kind of fine and also mergeSeeds are used in multiple scenarios and theoretically it's possible that in few of them we're not aware of this.

**Comment by mvorisek** [comment]
The impact should be analysed on main repos - simply create an instance in factory with zero arguments first.

Silently ignoring input is extremely dangerous. My strong preference is to throw in factory.

In a Atk, a lot of arguments are actually a seed (for Model, Field, View, ...), so these usecases should be fixable easily. All classes must be checked to support seed always as a last constructor instruction/expression - the suggested test above will check this.

If there are strong/unfixedable usecases to keep support of arguments in factory for object/instanced seeds, we should support them thru some magical method/trait that will accept and set them - like `_construct()` and call this method also from `__constructor`.

**Comment by DarkSide666** [comment]
So you're proposing to add something like this there?
```
if ($arguments) {
    throw new Exception(bla bla);
}
```

**Comment by mvorisek** [comment]
yes

**Comment by DarkSide666** [comment]
OK go ahead and then we will see what breaks and will have to fix that there.
