### ISSUE TITLE
Exception constructor trace should be never stored at all

### ISSUE THREAD

**Issue by mvorisek** [atk4/core#200]
Improve #188

@DarkSide666 ok?

compare trace of new Exception() and new \Exception(), the later has not __construct trace.

Current example:
![image](https://user-images.githubusercontent.com/2228672/82100796-fdb22880-970a-11ea-8b9a-9a70a0dcb88c.png)

**Comment by DarkSide666** [comment]
Important is that exception trace contains all info usable for developer to quickly track bug and fix it.
