### ISSUE TITLE
It should be possible to add hooks that do not require the source object as 1st param

### ISSUE THREAD

**Issue by mvorisek** [atk4/core#201]
Example of bad but typical usage:
![image](https://user-images.githubusercontent.com/2228672/82116034-e30d9d00-9766-11ea-803e-f333372c4570.png)

Example of better but still not good usage:
![image](https://user-images.githubusercontent.com/2228672/82116023-d5581780-9766-11ea-9b17-aab990e075c1.png)

Example of good usage:
![image](https://user-images.githubusercontent.com/2228672/82116046-fe78a800-9766-11ea-9c28-2fb57ee06e7c.png)

**Comment by DarkSide666** [comment]
Can you please tell why it's bad and/or good?

**Comment by mvorisek** [comment]
Of course - current situation - there are anonomyous functions with almost no typing thus no refactability in them, thus zero maintaible.

If types are declared, the basic refactoring work, but these types are usualy not specific enough.

The 1st argument is also very commnly skipped - this hook is called for method in the same object, of course, passing this again has negative value by definition.

The good new is, it can be solved :)

Wdyt?

**Comment by DarkSide666** [comment]
I'm completely OK with adding typing in `function (\atk4\ui\Lister $lister)`.

But your good example is not exactly good in all cases. I'm not sure about Lister, but for example in models it's like this:
```
$model->onHook('afterLoad', function (Model $m) use ($model) {
    // here $m will be loaded instance of model
    // but $model will be another - not loaded instance
    // so it should be passed as argument and not use()
});
```

**Comment by mvorisek** [comment]
@DarkSide666 Impossible, $this is now hardcored the 1st param...

**Comment by DarkSide666** [comment]
I guess you're right. It's probably the same object after all.
I just remember having issues with using `$this` inside hook callback methods. It was another model instance somehow. Probably my bad code was there :)

Anyway I don't see big difference between _better but still not good usage_ and _good usage_ then.  For me it's easier to understand if we pass object as 1st argument and not use() it.

**Comment by DarkSide666** [comment]
but adding typing of course is always good (if possible)

**Comment by mvorisek** [comment]
`$this` is context dependent, no callbacks (another PR), no context dependent Closures... :)

> but adding typing of course is always good (if possible)

- `use` is always clear what is passed
- if 1st param is not needed, it does not have to be skipped
- hinting/types does not have to be maintained
...

**Comment by DarkSide666** [comment]
Ok. But this again ir big BC break because probably many developers relied on having this object as 1st parameter for callbacks. So... maybe only in 3.x I guess :(

**Comment by mvorisek** [comment]
I can provide a scripted fixer for this, onHook(..., function() can be easily located.

**Comment by PhilippGrashoff** [comment]
There are a lot of
```
$this->onHook('afterSave', function($m) {
    $m->doSomething();
});
```

So your way of doing this would just be?
```
$this->onHook('afterSave', function() {
    $this->doSomething();
});
```

I remember using `$this` inside hooks is not good, as it leads to trouble with cloned models. I ran into that trouble myself, and its also stated in the Docs. How would you handle this situation?

**Comment by mvorisek** [comment]
- yes
- `$this` will be solved by requiring Closures, it is 100% safe if you know what you do and if we get rid of array callables

**Comment by mvorisek** [comment]
Maybe later or I need to come up with a solution that supports cloning/rebounding...
