### ISSUE TITLE
Allow/prioritize setter methods in DIContainerTrait::setDefaults()

### ISSUE THREAD

**Issue by mvorisek** [atk4/core#206]
https://github.com/atk4/core/blob/503ed2ff35865ca8b5499ecb61c95a6257b95621/src/DIContainerTrait.php#L50

proposal to call setXX() if exists instead of setting the XX property directly

**Comment by abbadon1334** [comment]
this is a logical idea, but usually i `setDefaults` and validate if all required dependency is in place correctly in constructor, and then when object is `add` to his owner i continue what i have to do during `init`, because only there i have the `$app`.

**Comment by mvorisek** [comment]
I do not want to pursue this issue now
