### ISSUE TITLE
Exception location is not dumped

### ISSUE THREAD

**Issue by mvorisek** [atk4/core#213]
![image](https://user-images.githubusercontent.com/2228672/83434215-52a7ab80-a43a-11ea-9702-853648e5b7fc.png)

**Comment by DarkSide666** [comment]
Yes that would be great. I have hit head against wall multiple times because of this missing last row :)

**Comment by mvorisek** [comment]
> I have hit head against wall multiple times because of this

then why it is not reported and fixed? :D

**Comment by DarkSide666** [comment]
Probably was to lazy :) :) :)
