### ISSUE TITLE
Throw if adding object to a collection but it was already added to another

### ISSUE THREAD

**Issue by mvorisek** [atk4/core#237]
This is a feature to throw if object has owner already.

Currently when object is added, full name is computed. Therefore, adding object to an additional collection is currently possible, but in reality the is only one owner, one name, so if allowed, it is wrong.

**Comment by mvorisek** [comment]
@DarkSide666 right, or do we need to support adding objects to multiple collections (but keeping the old owner)?

**Comment by DarkSide666** [comment]
Owner of object can be only one so I think it should belong to only one collection.
But need to think more about this. Maybe there is some usecase when object can and should be added to multiple collections.
