### ISSUE TITLE
Use mb_ functions

### ISSUE THREAD

**Issue by DarkSide666** [atk4/core#27]
Check if we have any of these methods and if so,then use their mb_ equivalent.
http://php.net/manual/en/ref.mbstring.php

Particularly test:
- [ ] passing utf8 values as parameters paramns from exceptions
- ..

**Comment by mvorisek** [comment]
@DarkSide666 You should be able to check/fix this extremely quickly using CS fixer - do not commit the config, but you can fix/review this in 180 seconds.

**Comment by DarkSide666** [comment]
not sure how. can you help with this?

**Comment by mvorisek** [comment]
> 
> 
> not sure how. can you help with this?

see `mb_str_functions` rule in https://github.com/FriendsOfPHP/PHP-CS-Fixer . Simply add it temporary to CS config, check the fixed and propose a PR if they make sense.

**Comment by DarkSide666** [comment]
ok, thanks
