### ISSUE TITLE
AppScopeTrait not working with model in recent develop

### ISSUE THREAD

**Issue by mkrecek234** [atk4/core#299]
See issue https://github.com/atk4/data/issues/798 for all descriptions.
In simple words:

In Persistence\Sql: 
use AppScopeTrait;

In app init: $this->db = new Persistence\Sql; $this->db->setApp($this)

In model: use AppScopeTrait.

Error in develop after 2.3.1 (before working): `TypeError: Argument 1 passed to Atk4\Crm\Model\Ticket::assertInstanceOfApp() must be an object, null given, called in vendor/atk4/core/src/AppScopeTrait.php on line 103`

**Comment by mvorisek** [comment]
Do not open multiple tickets for one issue!
