### ISSUE TITLE
MergeSeeds don't respect numeric keys defined as strings

### ISSUE THREAD

**Issue by DarkSide666** [atk4/core#65]
Example:
```
$years = ['2013', '2014'];
$a = new Object(['years'=>$years]);
var_dump($a->years); // returns [0=>'2013', 1=>'2014']
```

That's because `is_numeric('123')===true`. Must use `is_int('123')===false` almost everywhere.

In here:
https://github.com/atk4/core/blob/develop/src/FactoryTrait.php#L38
https://github.com/atk4/core/blob/develop/src/FactoryTrait.php#L59

Also `is_numeric` is quite widely used in DIContainer and in data, dsql and ui repositories. Need to review them too.

**Comment by romaninsh** [comment]
Unable to reproduce. Tried:

```
        $s1 = $this->factory(new SeedDITestMock(), ['foo'=>['bar', 'baz']]);
        $this->assertEquals(['bar', 'baz'], $s1->foo);
```

**Comment by romaninsh** [comment]
reviewing the example you have provided, it seems that it's correct. `[0=>'2013', 1=>'2014']` is identical to `['2013', '2014']` isn't it?

**Comment by DarkSide666** [comment]
I mean like this:

```
$years = ['2013'=>'2013', '2014'=>'2014'];
$a = new Object(['years'=>$years]);
var_dump($a->years); // returns [0=>'2013', 1=>'2014']
```

**Comment by romaninsh** [comment]
@DarkSide666 is this fixed ?

**Comment by DarkSide666** [comment]
Probably I was talking about these lines `array_filter($seed2, 'is_numeric', ARRAY_FILTER_USE_KEY); // with numeric keys`, but not sure what exactly was the problem.

I think it's good as it is now if nobody else have this problem for years.
