### ISSUE TITLE
Injecting "null" argument into constructor fails

### ISSUE THREAD

**Issue by romaninsh** [atk4/core#74]
Suppose you create a button using a seed:

``` php
$button = $app->add(['Button', 'icon'=>'book']);
```

it is created with no label and with an icon. Next consider this code:

``` php
$button = $app->add(['Button', 'lablabla', 'icon'=>'book']);
```

This works as expected. Button with label and icon is added. Next try this:

``` php
$button = $app->add(['Button', 'lablabla', 'big red', 'icon'=>'book']);
```

once again, this works as expected. A big red button with label and icon is added.

Now suppose you want to get rid of label, so you replace it with `null`

``` php
$button = $app->add(['Button', null, 'big red', 'icon'=>'book']);
```

But instead you find with a small button and label "big red". 

A current workaround is to specify 2nd argument as "false" or empty string but I think `null` should be equally acceptable.

**Comment by romaninsh** [comment]
(i'm not sure if the error is inside core or in UI, @DarkSide666 can you please investigate?)

**Comment by DarkSide666** [comment]
`false` and empty string `''` works as expected. `null` doesn't work.

**Comment by romaninsh** [comment]
it should skip named arguments if value is null.

**Comment by DarkSide666** [comment]
ok will fix that then
