### ISSUE TITLE
Exception: rename addMoreInfo() into addParam()

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/core#90]
Hi,

this is just a minor minor one. I think the method addMoreInfo() should be renamed to addParam(), as this is what it really does. This would make the name consistent with getParams() and params property.

Best regards
Philipp

**Comment by DarkSide666** [comment]
We can't drop old method because of compatibility, but I agree - `addParam` sounds better than `addMoreInfo`. We probably should have both of them and mark `addMoreInfo` as deprecated in some next major version.

**Comment by romaninsh** [comment]
i think "add more info" is more accurate, as our exceptions accumulate various information. We're not using extra infromation as parameter anywhere, so "addParam" would be missleading.

Also the important point is to make sure that this "additional information" is never displayed to a user as it may contain some critical / sensitive information.
