### ISSUE TITLE
refactor to use instanceOf instead of isset(_appScopeTrait)

### ISSUE THREAD

**Issue by romaninsh** [atk4/core#95]
For some weird reason initial implementation uses code that relies on presence of specific properties in the class in order to detect a trait.

If this can be refactored, then there would be less warnings and cleaner code:

![Screenshot 2019-06-19 at 14 57 32](https://user-images.githubusercontent.com/453929/59771960-c3de6500-92a2-11e9-859b-637d164e184b.png)

There are many occurrences, please create PR and make sure test-suite still works.

**Comment by abbadon1334** [comment]
i think the only way to do it is : https://php.net/manual/en/function.class-uses.php

bad news is that will return only first level traits.

i think the field check which is present in every atk trait is the only way to check it.

**Comment by DarkSide666** [comment]
Do `instanceof` work with traits at all?

**Comment by abbadon1334** [comment]
https://externals.io/message/101941

 Marco Pivetta Posted 1 year ago by Marco Pivetta — view source unread

This cannot work for a number of reasons:

    a trait is not a type, and does not practically exist at runtime
    trait defined API can be imported with changed/aliased names, breaking
    therefore the contact defined in the interface
    due to the previous point, inheriting a type from a trait becomes a
    dangerous BC boundary, easily broken by consumers of the trait when
    consumers alias or when the trait implementor adds a new interface
    implementation

My general suggestions:

    don't use traits
    don't use traits
    also, don't use traits
    remember to not use traits
    traits: don't
    things you shouldn't use on Betelgeuse and other systems: traits

Besides jokes, inheriting signatures together with implementations
(inheritance, abstract types) is less and less endorsed in the PHP
ecosystem, as it just increases coupling by a huge lot. At least from my
own experience, things are finally moving towards more composition over
inheritance.

**Comment by abbadon1334** [comment]
single way to solve the issue is to check for deep use of traits using a sort of class with a static method + a static array with key classname and value trait used to avoid check every time is called.

the other way is to continue like this and use type hint given by IDEs something like : 

```php
if (isset($this->_appScopeTrait) && isset($element->_appScopeTrait)) {
    $app = $this->app;
    /** @var App $app */
    $element->app = $app;
}
```

But i don't know if static analyzer recognize it.

Other solution is to encapsulate this checks in a bunch of function in namespace atk4\core, one function for every trait with specific return type 

i think this one which popup in my mind now is the best and much elegant of all.

**Comment by abbadon1334** [comment]
Just a test, to better show the problem : 

```php
trait firstLevelTrait {
	
}


trait secondLevelTrait {
	
}


trait nestedLevelTrait {
	use firstLevelTrait;
	use secondLevelTrait;
}


class withFirstLevelTrait {
	use firstLevelTrait;
}


class withSecondLevelTrait extends withFirstLevelTrait {
	use secondLevelTrait;
}


class withNestedLevelTrait {
	use nestedLevelTrait;
}

class extendFirstLevelTrait extends withFirstLevelTrait {}

$first = new withFirstLevelTrait();
$second = new withSecondLevelTrait();
$nested = new withNestedLevelTrait();
$extend = new extendFirstLevelTrait();

var_dump(class_uses($first));
var_dump(class_uses($second));
var_dump(class_uses($nested));
var_dump(class_uses($extend));
```
will output :
```
array(1) {
  ["firstLevelTrait"]=>
  string(15) "firstLevelTrait"
}
array(1) {
  ["secondLevelTrait"]=>
  string(16) "secondLevelTrait"
}
array(1) {
  ["nestedLevelTrait"]=>
  string(16) "nestedLevelTrait"
}
array(0) {
}
```

**Comment by romaninsh** [comment]
i see. I'll close this then.

**Comment by romaninsh** [comment]
Here is another alternative: https://stackoverflow.com/a/36516565/204819
